Student Course Registration Site/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views


app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about', views.about,name='about'),
    path(r'<int:top_no>/', views.detail,name='detail'),
    path(r'courses',views.courses, name='courses'),
    path(r'courses/<int:cour_id>/',views.coursedetail, name='coursedetail'),
    path(r'place_order',views.place_order, name='placeorder'),
    path(r'login', views.user_login, name='login'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'myaccount', views.myaccount, name='myaccount'),
    path(r'register', views.register, name='register'),
    path(r'password_reset', views.password_reset_request, name='password_reset'),


]

Student Course Registration Site/mysiteS20/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path(r'myapp/', include('myapp.urls')),

                  url(r'^$', TemplateView.as_view(template_name='myapp/index.html'),
                      name='home'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Student Course Registration Site/myapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.safestring import mark_safe


class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, blank=False, null=False, default=" ")

    def __str__(self):
        return self.name


def limit(value):
    if not 100 <= value <= 200:
        raise ValidationError(('Please enter value between 100 and 200 , %(value)  is not in the defined range '),
                              params={'value': value}, )


class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[limit])
    hours = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def __str__(self):
        return self.name

    def discount(self):
        return (float(self.price) * 0.9)


class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
                    ('CG', 'Calgery'),
                    ('MR', 'Montreal'),
                    ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=20, choices=CITY_CHOICES, default='Windsor')
    interested_in = models.ManyToManyField(Topic)
    profile_pic = models.ImageField(upload_to='profile', null=True, blank=True)

    def image_tag(self):
        if self.profile_pic:
            return mark_safe('<img src="%s" style="width: 200px; height:200px;" />' % self.profile_pic.url)
        else:
            return 'No Image Found'
    image_tag.short_description = 'Image'

    def __str__(self):
        return self.get_full_name()


class Order(models.Model):
    ORDER_STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Order Confirmed')]
    course = models.ForeignKey(Course, related_name='course', on_delete=models.CASCADE)
    student = models.ForeignKey(Student, related_name='student', on_delete=models.CASCADE, max_length=200)
    levels = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=1)
    order_date = models.DateField(default=datetime.date.today)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=False, editable=False,
                                      default=0)

    def __str__(self):
        return str(self.course)

    def total_cost(self):
        cname = Course.objects.get(name=self.course)
        total_price = self.total_price + cname.price
        return self.total_price

Student Course Registration Site/myapp/forms.py
from django import forms
from myapp.models import Order, Student, Topic
from django.forms import CheckboxSelectMultiple


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'student',
            'course',
            'levels',
            'order_date'
        ]

    student = forms.RadioSelect()
    order_date = forms.DateField(widget=forms.SelectDateWidget)


class InterestForm(forms.Form):
    interested = forms.ChoiceField(widget=forms.RadioSelect(), choices=[('1', 'Yes'), ('0', 'No')])
    levels = forms.IntegerField(initial=1)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments')


class loginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'city',
            'password',
            'username',
            'interested_in',
            'profile_pic'
        ]
        widgets = {
            'interested_in': CheckboxSelectMultiple(),
        }

Student Course Registration Site/myapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from urllib.parse import urlencode
from .models import Topic, Course, Student,User
from .forms import *
import datetime,smtplib,string,random

def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    course_list = Course.objects.all().order_by('-price')[:5]
    if request.session.get('last_login',default=None) is None:
        login_time="Your last login was more than one hour ago"
    else:
        login_time=request.session.get('last_login')
    return render(request, 'myapp/index.html', {'top_list': top_list, 'course_list': course_list,'login_time':login_time})


def about(request):
    data = "This is an E-Learning WebApp! Search our Topics to find all available Courses."
    no_times = 1
    response = render(request, 'myapp/about.html', {'data': data,'visit':no_times})
    if request.COOKIES.get("about_visits", None) is None:
        response.set_cookie('about_visits', no_times, expires=300)
    else:
        cnt=request.COOKIES.get("about_visits")
        cnt=int(cnt)+1
        response= render(request, 'myapp/about.html', {'data': data, 'visit':cnt})
        response.set_cookie('about_visits', cnt, expires=300)
    return response


def detail(request, top_no):
    response = HttpResponse()
    topic = get_object_or_404(Topic, pk=top_no)
    all_courses = Course.objects.filter(topic__name=topic.name)
    return render(request, 'myapp/detail.html', {'topic': topic, 'all_courses': all_courses})


def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})


def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.levels <= order.course.stages:
                if (order.course.price > 150.00):
                    Course.discount(order.course)
                order.save()
                msg = 'Your course has been ordered successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist})


def coursedetail(request, cour_id):
    courdetail = Course.objects.get(pk=cour_id)
    if request.method == 'POST':
        form = InterestForm((request.POST))
        if form.is_valid():
            if form['interested'] == 1:
                courdetail.interested = courdetail.interested + 1
                courdetail.save()
        return redirect('myapp:index')
    else:
        form = InterestForm()
        return render(request, 'myapp/coursedetail.html', {'form': form, 'courdetail': courdetail})


def user_login(request):
    context = {}
    context['form'] = loginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                user_object=User.objects.get(username=username)
                time = datetime.datetime.now()
                request.session['last_login']= str(time)
                request.session['u_id']=user_object.id
                # request.session.set_expiry(3600)
                if 'next' in request.POST:
                    next=request.POST.get('next')
                    return redirect('myapp:'+next)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html', context)


@login_required
def user_logout(request):
    del request.session['u_id']
    request.session.flush()
    return redirect('myapp:index')

def myaccount(request):
    current_user = request.user
    if request.user.is_authenticated:
        if not current_user.id == 1:
            first_name = current_user.first_name
            last_name = current_user.last_name
            ordered_course = Order.objects.filter(student_id=current_user.id).values_list('course__name', flat=True)
            interested = Student.objects.filter(id=current_user.id).values_list('interested_in__courses__name', flat=True)
            return render(request, 'myapp/myaccount.html',
                          {'ordered_course': ordered_course, 'first_name': first_name, 'last_name': last_name,
                           'interested': interested})
        else:
            return HttpResponse('You are not a registered student!')
    else:
        base_url=reverse('myapp:login')
        query_string=urlencode({'next':'myaccount'})
        url='{}?{}'.format(base_url,query_string)
        return redirect(url)

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user=form.save(commit=False)
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()
            form.save()
            return redirect('myapp:login')
    form=RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})

def password_reset_request(request):
    context=""
    if request.method == "POST":
        email = request.POST['email']
        std_obj=Student.objects.filter(email=email)
        if std_obj.exists():
            print("ok")
            s=smtplib.SMTP('smtp.gmail.com',587)
            s.starttls()
            s.login("XXXXX@gmail.com","XXXXX")
            rand_password=''.join(random.choices(string.ascii_uppercase + string.ascii_lowercase+ string.digits, k=10))
            std_obj = Student.objects.get(email=email)
            std_obj.set_password(rand_password)
            std_obj.save()
            message="Your new password is: "+rand_password+". Please use this password to login again."
            s.sendmail("XXXXX@gmail.com",email,message)
            s.quit()
            return render(request,"myapp/password_send.html")
        else:
            context="Your email address was not found. Please try again!"
    return render(request,'myapp/password_reset.html',{'context':context})

Student Course Registration Site/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>

<p>{{ data }}</p>
<p><a href="{% url 'myapp:index' %}">Index page</a></p>
<p><a href="/myapp">Index page</a></p>
</body>
</html>

Student Course Registration Site/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'myapp:index' %}">E-Learning</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     <li class="nav-item active"><a class="nav-link" href="{% url 'myapp:index' %}">Home</a></li>
        <li class="nav-item active"><a class="nav-link" href="/myapp/about">About</a></li>

        <li class="nav-item active"><a class="nav-link" href="{% url 'myapp:courses' %}">Courses</a></li>
        {% if request.user.is_authenticated %}
            <li class="nav-item active" ><a class="nav-link" href="{% url 'myapp:myaccount' %}">My Account</a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'myapp:logout' %}">Logout</a></li>

        {% else %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'myapp:login' %}">Login</a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'myapp:register' %}">Register</a></li>

        {% endif %}
    </ul>
</div>
</nav>

<div>
    <h2 style="padding-top:10px; font-size: 25px; "> {% block myhdg %} Hello {{ user.first_name }} {{ user.last_name }} {% endblock %}</h2>
    {% block body_block %}*** {% endblock %}
</div>
<hr/>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Student Course Registration Site/myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}

    <p>
        {{ courdetail.name}}<br>
        {{ courdetail.price }}<br>
        {{ courdetail.interested }}<br>
        {% if courdetail.for_everyone is False%}
            <b>This course is not for everyone!</b>
        {% endif %}
    </p>


    <form method="POST" >
    {% csrf_token %}
        {{ form.as_p }}
       <div class="form-group">
           <button style="width: 85px" class="btn btn-lg btn-primary btn-block">Save</button>
       </div>
    </form>
{% endblock %}

Student Course Registration Site/myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h5> List Of Courses</h5>
    <ol>
        {% for courses in courlist %}
             <li><a href="{% url 'myapp:coursedetail' courses.id %}">{{ courses }}</a></li>
        {% endfor %}
    </ol>
    <button style="width :250px" class="btn btn-lg btn-primary btn-block" ><a style="color: white" href="{% url 'myapp:placeorder' %}">Click here to place order</a></button>
{% endblock %}

Student Course Registration Site/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
   <h5>List of Courses ::</h5>
    <ol>
        {% for i in all_courses %}
            <li> {{ i }} </li>
        {% endfor %}
    </ol>

{% endblock %}

Student Course Registration Site/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>

<h5>Category :: {{ topic.category }}</h5>

<h5>List of Courses ::</h5>
    <ol>
        {% for i in all_courses %}
            <li> {{ i }} </li>
        {% endfor %}
    </ol>
<p><a href="{% url 'myapp:index' %}">Index page</a></p>

</body>
</html>

Student Course Registration Site/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>E-Learning WebApp!</title>
</head>
<body>

{% if top_list %}
    <h5>List of Topics</h5>
    <ol>
        {% for top in top_list %}
            <li><a href="{% url 'myapp:detail' top.id %}">{{ top.name }}</a></li>
        {% endfor %}
    </ol>
{% else %}
    <strong>There are no available topics!</strong>
{% endif %}
<br>
<h5>List of Courses</h5>
<ol>
{% for course in course_list %}
    <li>{{ course }}</li>
{% endfor %}
</ol>

<p><a href="{% url 'myapp:about' %}">About page</a></p>
</body>
</html>

Student Course Registration Site/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}


{% block body_block %}
    <div class="container" style="margin-top: 20px;">
	<div class="row">
		<h3 style="width:100% ;
				   text-align: center"> Login</h3>
			<div style="width: 30%; margin: 30px auto;">
                <form id="login-form" method="POST" action="{% url 'myapp:login' %}" >
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if request.GET.next %}
                        <div class="form-group">
                            <input id= "1" class="form-control" type="hidden" name="next" value="{{ request.GET.next }}">
                        </div>
                    {% endif %}
                    <div class="form-group">
                       <button class="btn btn-lg btn-primary btn-block">Login</button>
                    </div>
                    <a href="{%  url 'myapp:password_reset' %}"> Forgot Password?</a>
                    <span style="margin-left:20px ">New User? <a href="{% url 'myapp:register' %}">Sign Up!</a></span>
                </form>

            </div>
    </div>
    </div>

{% endblock %}

Student Course Registration Site/myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h5> First Name: {{ first_name }} </h5>
    <h5>Last Name: {{ last_name }}</h5>
    <h5>List of Courses Ordered:</h5>
    <ol>
        {% for i in ordered_course %}
            <li> {{ i }} </li>
        {% endfor %}
    </ol>

    <h5>List of Interested Topics:</h5>
    <ol>
        {% for i in interested %}
            <li> {{ i }} </li>
        {% endfor %}
    </ol>


{% endblock %}

Student Course Registration Site/myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% csrf_token %}
    {{ msg }}
{% endblock %}

Student Course Registration Site/myapp/templates/myapp/password_reset.html
{% extends 'myapp/base.html' %}
{% block body_block %}


    <h5>Please enter your email id for resetting your password.</h5>
    <hr>
    <form action="" method="post">
        {% csrf_token %}

        <div>
            <label for="email">Email:</label>
            <input type="email" name="email" placeholder="Enter your email">
            </div><br>
                <button type="submit" class="btn btn-primary">Reset Password</button>

    </form>

    <h2>
    {{ context }}
    </h2>
{% endblock %}

Student Course Registration Site/myapp/templates/myapp/password_send.html
{% extends 'myapp/base.html' %}
{% block body_block %}

    <h5>A new password has been sent to you. Please check your email.</h5>
    <p><a href="{% url 'myapp:login' %}" ><button type="button" class="btn btn-primary">Login</button></a></p>

{% endblock %}

Student Course Registration Site/myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% for course in courlist %}
        {{ course }}<br>
    {% endfor %}

    <form method="POST">
        {% csrf_token %}
        <br>
    <hr>
        {{ form.as_p }}

        <div class="form-group">
            <button style="width: 130px" class="btn btn-lg btn-primary btn-block">Place Order</button>
        </div>
    </form>
{% endblock %}

Student Course Registration Site/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block body_block %}
   <h4>Registration Form</h4>
    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
         <div class="form-group">
             <button style="width: 85px" class="btn btn-lg btn-primary btn-block">Save</button>
         </div>
    </form>
{% endblock %}